# Generated by Django 4.0.4 on 2022-11-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=255)),
                ('socials', models.CharField(max_length=64)),
                ('services', models.CharField(max_length=255)),
                ('budget', models.CharField(max_length=16)),
                ('details', models.CharField(max_length=255)),
                ('traffic', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Quotas',
                'unique_together': {('name', 'email')},
            },
        ),
    ]
