# Generated by Django 4.0.4 on 2022-11-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0002_partner_alter_quota_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='followers',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
