# Generated by Django 4.0.4 on 2022-11-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0004_alter_partner_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='followers',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
