# Generated by Django 4.0.4 on 2022-11-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0005_alter_partner_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='followers',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
