# Generated by Django 4.0.4 on 2022-11-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0006_alter_partner_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together=set(),
        ),
    ]
